muypicky/menus/urls.py
from django.conf.urls import url


from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView,
    )


app_name = 'menus'
urlpatterns = [
    url(r'^$', ItemListView.as_view(), name='list'),
    url(r'^create$', ItemCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[\w-]+)/$', ItemDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[\w-]+)/edit$', ItemUpdateView.as_view(), name='update')
]

muypicky/restaurants/urls.py
from django.conf.urls import url


from .views import (
    Restaurant_listview,
    Restaurant_detailview,
    RestaurantCreateView,
    RestaurantUpdateView,
    )


app_name = 'restaurants'
urlpatterns = [
    url(r'^$', Restaurant_listview.as_view(), name='restaurantslist'),
    url(r'^create$', RestaurantCreateView.as_view(), name='restaurantscreate'),
    url(r'^(?P<slug>[\w-]+)/$', Restaurant_detailview.as_view(), name='detailrestaurant'),
    url(r'^(?P<slug>[\w-]+)/edit/$', RestaurantUpdateView.as_view(), name='update')
]

muypicky/templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

muypicky/templates/snippets/form-snippet.html
{% if form.errors.non_field_errors %}
{{ form.errors.non_field_errors }}
{% endif %}
<form method='POST'> {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Save</button>
</form>

muypicky/templates/snippets/js.html
<script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

muypicky/templates/snippets/nav.html
<div class='container'>
<div class='row text-center'>
<div clsas='col-sm-6 col-sm-offset-3'>
<h1>MuyPicky.com</h1>
    <a href='{% url "home" %}'>Home</a>
    <a href='{% url "about" %}'>About</a>
    <a href='{% url "contact" %}'>Contact</a>


    {% if not request.user.is_authenticated %}
    <a href='{% url "login" %}'>Login</a>
    <a href='{% url "register" %}'>Register</a>
    {% endif %}

    {% if request.user.is_authenticated %}
    <a href='{% url "restaurants:restaurantslist" %}'>Restaurants</a>
    <a href='{% url "restaurants:restaurantscreate" %}'>Create Restaurant</a>
    <a href='{% url "menus:list" %}'>Menus</a>
    <a href='{% url "menus:create" %}'>Create menus item</a>
    <a href='{% url "logout" %}'>Logout</a>

    {% endif %}

</div>
</div>

</div><hr/>

muypicky/templates/snippets/sidebar.html
<ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
</ul>