muypicky/menus/urls.py
from django.conf.urls import url


from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView,
    )


app_name = 'menus'
urlpatterns = [
    url(r'^$', ItemListView.as_view(), name='list'),
    url(r'^create$', ItemCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[\w-]+)/$', ItemDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[\w-]+)/edit$', ItemUpdateView.as_view(), name='update')
]

muypicky/muypicky/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import include, url
from django.views.generic import TemplateView


from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view
from menus.views import HomeView




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/$',RegisterView.as_view(), name='register'),
    url(r'^activate/(?P<code>[A-Z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^login/',LoginView.as_view(redirect_field_name='home.html'), name='login'),
    url(r'^logout/', LogoutView.as_view(redirect_field_name='/home'), name='logout'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^contact/$', TemplateView.as_view(template_name ='contact.html'), name='contact'),
    url(r'^about/$', TemplateView.as_view(template_name ='about.html'), name='about'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^menus/', include('menus.urls', namespace='menus')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),


]
# (?P<id>\d+)/

muypicky/templates/about.html
{% extends "base.html" %}

{% block head_title %}About || {{ block.super }}{% endblock head_title %}



{% block content %}
<h1>About</h1>

{% include 'snippets/sidebar.html' %}

{% endblock  %}

muypicky/templates/base.html
<!DOCTYPE html>
<html lang=en>

<head>
    <title>{% block head_title %}MuyPicky.com{% endblock head_title %}</title>
    {% include 'snippets/css.html' %}
</head>
<body>
    {% include 'snippets/nav.html' %}
    {% if messages %}
    <div class="alert messages text-center">
        {% for message in messages %}
        <b>{{ message }}</b><br/>
        {% endfor %}

    </div>
    {% endif %}

    <div class='container'>
        {% block content %}{% endblock content %}
    </div>


    {% include 'snippets/js.html' %}
</body>
</html>

muypicky/templates/contact.html
{% extends "base.html" %}

{% block head_title %}Contact || {{ block.super }}{% endblock head_title %}


{% block content %}
<h1>Content</h1>
{% include 'snippets/sidebar.html' %}
<a href='mailto:youremail@gmail.com'>Email us</a>
{% endblock  %}

muypicky/templates/form.html
{% extends "base.html" %}

{% block head_title %}{{ title }} | {{ block.super}}{% endblock head_title %}

{% block content %}
<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ title }}</h1>

{% include 'snippets/form-snippet.html' %}
</div>

</div>
{% endblock %}

muypicky/templates/home.html
{% extends "base.html" %}

{% block content %}
{% if not request.user.is_authenticated %}
    <div class='row'>
    <div class='col-sm-6 col-sm-offset-3 text-center'>
    <p class='lead'>
    Share your pickiness with your friends. Add the restaurants add menu items like most so they get it right every time.<br/>

    <a href='{% url "register" %}'>Join us</a> 
    </p>
    <hr/>
    </div>

    </div>
{% endif %}
<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>

    {{ num }}

</div>
</div>


<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h3>Recent Items</h3>
{% for obj in object_list %}


        <div class='thumbnail'> 
            <h3><a href='{% url "profiles:detail" username=obj.user.username %}'>{{ obj.user.username }}</a></h3>
            <h4>{{ obj.name }}</h4>
            <p><a href='{% url "profiles:detail" username=obj.user.username %}?q={{ obj.restaurant.title }}'>{{ obj.restaurant.title }}</a>| <a href='{% url "profiles:detail" username=obj.user.username %}?q={{ obj.restaurant.location }}'>{{ obj.restaurant.location }}</a> | <a href='{% url "profiles:detail" username=obj.user.username %}?q={{ obj.restaurant.category }}'>{{ obj.restaurant.category }}</a></p>
            <p>
            <b>{{ obj.name }}:</b> with
             {% for ing in obj.get_contents %}
                <a href='{% url "profiles:detail" username=obj.user.username %}?q={{ ing}}'>{{ ing}}</a>
            {% endfor %}
            </p>
        </div>



{% endfor %}

</div>
</div>
{% endblock content %}